<a href="https://colab.research.google.com/github/Aishwarya-221810309012/my-projects/blob/main/Aishwarya_Bvn(AI_Mini_Project).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROJECT : MAKE A HEART DISEASE PREDICTIVE MODEL TO PREDICT ON THE "TARGET" COLUMN OF THE DATASET**

In [ ]:
import pandas as pd
import numpy as np

## Step 1 :Read the csv file and convert into the dataframe.

In [ ]:
df=pd.read_csv("heart.csv")

In [ ]:
df

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
df.shape

(303, 14)

#Step 2: We have to clean the data.This can be done in two ways


*   isnull method
*   sum method





In [ ]:
df=pd.read_csv("heart.csv")

In [ ]:
df

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
df.isnull()

age    sex     cp  trestbps   chol  ...  oldpeak  slope     ca   thal  target
0    False  False  False     False  False  ...    False  False  False  False   False
1    False  False  False     False  False  ...    False  False  False  False   False
2    False  False  False     False  False  ...    False  False  False  False   False
3    False  False  False     False  False  ...    False  False  False  False   False
4    False  False  False     False  False  ...    False  False  False  False   False
..     ...    ...    ...       ...    ...  ...      ...    ...    ...    ...     ...
298  False  False  False     False  False  ...    False  False  False  False   False
299  False  False  False     False  False  ...    False  False  False  False   False
300  False  False  False     False  False  ...    False  False  False  False   False
301  False  False  False     False  False  ...    False  False  False  False   False
302  False  False  False     False  False  ...    False  False  False  False   False

[303 rows x 14 columns]

In [ ]:
df.isnull().sum(axis="rows")

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

#Here the data is already clean

In [ ]:
df.shape

(303, 14)

In [ ]:
y=df["target"]

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
x=df[["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal"]]

In [ ]:
x

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

# Step 3: we are building a  classification model to predict the heart disease.Two changes are required


*   Increase the number of neurons in output layer(One-Hot Encoding technique)
*  Convert the values in neurons of output layer to probability values.(Using activation function - softmax)







In [ ]:
y=to_categorical(y)

In [ ]:
y.shape

(303, 2)

In [ ]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [ ]:
x.shape

(303, 13)

In [ ]:
x

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

# 1. **SPECIFY THE ARCHITECTURE**

> (a) Type of the Model -> Sequential Model

> (b) Type of layers involved in the model -> Dense layers

> (c) Number of layers involved in the model -> 3

> (d) Number of neurons in each layer ->
1. Input layer = 13 neurons
2. Hidden layer = 60 neurons
3. Output layer = 2  neurons

> (e) Activation Function -> relu(Rectified Linear activation function) and softmax

























  



In [ ]:
from keras.layers import Dense

In [ ]:
from keras.models import Sequential

In [ ]:
x.shape

(303, 13)

In [ ]:
model=Sequential()
model.add(Dense(60,activation="relu",input_shape=(13,)))
model.add(Dense(2,activation="softmax"))

## 2. **COMPILE THE MODEL**

> (a) Loss Function -> Categorical crossentropy

> (b) Optimize the weights -> adam formula








In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

# 3.**FIT THE MODEL**

> (a) Pass the data(Features and Target)

> (b) Iterations of forward and Backward Propagation.






In [ ]:
model.fit(x,y,epochs=30)

Epoch 1/30
10/10 [==============================] - 0s 2ms/step - loss: 0.3911 - accuracy: 0.8218
Epoch 2/30
10/10 [==============================] - 0s 2ms/step - loss: 0.3792 - accuracy: 0.8416
Epoch 3/30
10/10 [==============================] - 0s 2ms/step - loss: 0.4559 - accuracy: 0.7822
Epoch 4/30
10/10 [==============================] - 0s 2ms/step - loss: 0.4622 - accuracy: 0.8020
Epoch 5/30
10/10 [==============================] - 0s 2ms/step - loss: 0.3933 - accuracy: 0.8218
Epoch 6/30
10/10 [==============================] - 0s 2ms/step - loss: 0.4347 - accuracy: 0.7921
Epoch 7/30
10/10 [==============================] - 0s 2ms/step - loss: 0.3907 - accuracy: 0.8251
Epoch 8/30
10/10 [==============================] - 0s 2ms/step - loss: 0.3941 - accuracy: 0.8152
Epoch 9/30
10/10 [==============================] - 0s 2ms/step - loss: 0.4335 - accuracy: 0.7921
Epoch 10/30
10/10 [==============================] - 0s 2ms/step - loss: 0.3880 - accuracy: 0.8416
Epoch 11/30
10/10 [

 #  4. **PREDICT ON SAMPLE DATA**

In [ ]:
x

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

In [ ]:
data=pd.DataFrame({"age":[75],"sex":[1],"cp":[2],"trestbps":[162],"chol":[230],"fbs":[1],"restecg":[1],"thalach":[180],"exang":[1],"oldpeak":[3.2],"slope":[2],"ca":[3],"thal":[2]})

In [ ]:
data

age  sex  cp  trestbps  chol  fbs  ...  thalach  exang  oldpeak  slope  ca  thal
0   75    1   2       162   230    1  ...      180      1      3.2      2   3     2

[1 rows x 13 columns]

In [ ]:
model.predict(data)

array([[0.9179939 , 0.08200606]], dtype=float32)

In [ ]:
data=pd.DataFrame({"age":[30],"sex":[0],"cp":[4],"trestbps":[118],"chol":[200],"fbs":[0],"restecg":[1],"thalach":[130],"exang":[0],"oldpeak":[0.3],"slope":[1],"ca":[1],"thal":[3]})

In [ ]:
data

age  sex  cp  trestbps  chol  fbs  ...  thalach  exang  oldpeak  slope  ca  thal
0   30    0   4       118   200    0  ...      130      0      0.3      1   1     3

[1 rows x 13 columns]

In [ ]:
model.predict(data)

array([[0.02856844, 0.97143155]], dtype=float32)